# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_experimentWindow(object):
    def setupUi(self, experimentWindow):
        experimentWindow.setObjectName("experimentWindow")
        experimentWindow.resize(1229, 874)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("web.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        experimentWindow.setWindowIcon(icon)
        self.centralWidge = QtWidgets.QWidget(experimentWindow)
        self.centralWidge.setObjectName("centralWidge")
        self.userScroll = QtWidgets.QScrollArea(self.centralWidge)
        self.userScroll.setGeometry(QtCore.QRect(20, 30, 435, 781))
        self.userScroll.setMaximumSize(QtCore.QSize(435, 16777215))
        self.userScroll.setWidgetResizable(True)
        self.userScroll.setObjectName("userScroll")
        self.userInput = QtWidgets.QWidget()
        self.userInput.setGeometry(QtCore.QRect(0, 0, 433, 779))
        self.userInput.setObjectName("userInput")
        self.settingsFrame = QtWidgets.QGroupBox(self.userInput)
        self.settingsFrame.setGeometry(QtCore.QRect(10, 10, 400, 119))
        self.settingsFrame.setMinimumSize(QtCore.QSize(400, 100))
        self.settingsFrame.setMaximumSize(QtCore.QSize(16777215, 400))
        self.settingsFrame.setObjectName("settingsFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settingsFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settingsInput = QtWidgets.QGridLayout()
        self.settingsInput.setObjectName("settingsInput")
        self.unameInput = QtWidgets.QLineEdit(self.settingsFrame)
        self.unameInput.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.unameInput.setAutoFillBackground(False)
        self.unameInput.setInputMask("")
        self.unameInput.setText("")
        self.unameInput.setFrame(True)
        self.unameInput.setCursorPosition(0)
        self.unameInput.setReadOnly(False)
        self.unameInput.setClearButtonEnabled(False)
        self.unameInput.setObjectName("unameInput")
        self.settingsInput.addWidget(self.unameInput, 0, 1, 1, 1)
        self.expNum = QtWidgets.QLabel(self.settingsFrame)
        self.expNum.setMaximumSize(QtCore.QSize(16777215, 10))
        self.expNum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.expNum.setObjectName("expNum")
        self.settingsInput.addWidget(self.expNum, 1, 0, 1, 1)
        self.unameLabel = QtWidgets.QLabel(self.settingsFrame)
        self.unameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unameLabel.setObjectName("unameLabel")
        self.settingsInput.addWidget(self.unameLabel, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.settingsFrame)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.settingsInput.addWidget(self.label_13, 1, 1, 1, 1)
        self.defaultCheck = QtWidgets.QCheckBox(self.settingsFrame)
        self.defaultCheck.setObjectName("defaultCheck")
        self.settingsInput.addWidget(self.defaultCheck, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.settingsInput)
        self.commFrame = QtWidgets.QGroupBox(self.userInput)
        self.commFrame.setGeometry(QtCore.QRect(10, 130, 400, 182))
        self.commFrame.setMinimumSize(QtCore.QSize(400, 100))
        self.commFrame.setMaximumSize(QtCore.QSize(16777215, 400))
        self.commFrame.setObjectName("commFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.commFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.commInput = QtWidgets.QGridLayout()
        self.commInput.setObjectName("commInput")
        self.teensyInput = QtWidgets.QLineEdit(self.commFrame)
        self.teensyInput.setInputMask("")
        self.teensyInput.setText("")
        self.teensyInput.setFrame(True)
        self.teensyInput.setCursorPosition(0)
        self.teensyInput.setReadOnly(False)
        self.teensyInput.setObjectName("teensyInput")
        self.commInput.addWidget(self.teensyInput, 0, 1, 1, 1)
        self.integration = QtWidgets.QLabel(self.commFrame)
        self.integration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.integration.setObjectName("integration")
        self.commInput.addWidget(self.integration, 1, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.commFrame)
        self.checkBox_2.setObjectName("checkBox_2")
        self.commInput.addWidget(self.checkBox_2, 2, 1, 1, 1)
        self.integrationInput = QtWidgets.QLineEdit(self.commFrame)
        self.integrationInput.setInputMask("")
        self.integrationInput.setText("")
        self.integrationInput.setFrame(True)
        self.integrationInput.setCursorPosition(0)
        self.integrationInput.setReadOnly(False)
        self.integrationInput.setObjectName("integrationInput")
        self.commInput.addWidget(self.integrationInput, 1, 1, 1, 1)
        self.teensyPort = QtWidgets.QLabel(self.commFrame)
        self.teensyPort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.teensyPort.setObjectName("teensyPort")
        self.commInput.addWidget(self.teensyPort, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.commInput)
        self.line1 = QtWidgets.QFrame(self.userInput)
        self.line1.setGeometry(QtCore.QRect(50, 320, 319, 3))
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.uploadFile = QtWidgets.QCommandLinkButton(self.userInput)
        self.uploadFile.setEnabled(True)
        self.uploadFile.setGeometry(QtCore.QRect(50, 320, 319, 50))
        self.uploadFile.setMaximumSize(QtCore.QSize(16777215, 50))
        self.uploadFile.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.uploadFile.setAutoFillBackground(False)
        self.uploadFile.setAutoDefault(False)
        self.uploadFile.setObjectName("uploadFile")
        self.line3 = QtWidgets.QFrame(self.userInput)
        self.line3.setGeometry(QtCore.QRect(40, 450, 319, 3))
        self.line3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line3.setObjectName("line3")
        self.startButton = QtWidgets.QPushButton(self.userInput)
        self.startButton.setGeometry(QtCore.QRect(50, 370, 319, 28))
        self.startButton.setObjectName("startButton")
        self.progressBar = QtWidgets.QProgressBar(self.userInput)
        self.progressBar.setGeometry(QtCore.QRect(50, 400, 319, 24))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.line4 = QtWidgets.QFrame(self.userInput)
        self.line4.setGeometry(QtCore.QRect(40, 540, 319, 20))
        self.line4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line4.setObjectName("line4")
        self.saveBox = QtWidgets.QGroupBox(self.userInput)
        self.saveBox.setGeometry(QtCore.QRect(10, 560, 401, 211))
        self.saveBox.setObjectName("saveBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.saveBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 30, 271, 135))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.saveGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.saveGrid.setContentsMargins(0, 0, 0, 0)
        self.saveGrid.setObjectName("saveGrid")
        self.phaseCheck = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.phaseCheck.setObjectName("phaseCheck")
        self.saveGrid.addWidget(self.phaseCheck, 2, 1, 1, 1)
        self.fourierCheck = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.fourierCheck.setObjectName("fourierCheck")
        self.saveGrid.addWidget(self.fourierCheck, 1, 1, 1, 1)
        self.pdCheck = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.pdCheck.setObjectName("pdCheck")
        self.saveGrid.addWidget(self.pdCheck, 3, 1, 1, 1)
        self.riverCheck = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.riverCheck.setObjectName("riverCheck")
        self.saveGrid.addWidget(self.riverCheck, 0, 1, 1, 1)
        self.riverLoc = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.riverLoc.setObjectName("riverLoc")
        self.saveGrid.addWidget(self.riverLoc, 0, 0, 1, 1)
        self.fourierLoc = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.fourierLoc.setObjectName("fourierLoc")
        self.saveGrid.addWidget(self.fourierLoc, 1, 0, 1, 1)
        self.phaseLoc = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.phaseLoc.setObjectName("phaseLoc")
        self.saveGrid.addWidget(self.phaseLoc, 2, 0, 1, 1)
        self.pdLoc = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pdLoc.setObjectName("pdLoc")
        self.saveGrid.addWidget(self.pdLoc, 3, 0, 1, 1)
        self.saveCheck = QtWidgets.QCheckBox(self.saveBox)
        self.saveCheck.setGeometry(QtCore.QRect(20, 180, 181, 20))
        self.saveCheck.setObjectName("saveCheck")
        self.progressText = QtWidgets.QLabel(self.userInput)
        self.progressText.setGeometry(QtCore.QRect(40, 460, 311, 91))
        self.progressText.setAutoFillBackground(False)
        self.progressText.setText("")
        self.progressText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.progressText.setObjectName("progressText")
        self.userScroll.setWidget(self.userInput)
        self.plotFrame = QtWidgets.QFrame(self.centralWidge)
        self.plotFrame.setGeometry(QtCore.QRect(460, 30, 1040, 781))
        self.plotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotFrame.setObjectName("plotFrame")
        self.tabs = QtWidgets.QTabWidget(self.plotFrame)
        self.tabs.setGeometry(QtCore.QRect(0, 0, 761, 781))
        self.tabs.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.tabs.setObjectName("tabs")
        self.riverTab = QtWidgets.QWidget()
        self.riverTab.setObjectName("riverTab")
        self.mplRiver = MplWidget(self.riverTab)
        self.mplRiver.setGeometry(QtCore.QRect(0, 0, 761, 761))
        self.mplRiver.setMinimumSize(QtCore.QSize(500, 500))
        self.mplRiver.setAutoFillBackground(True)
        self.mplRiver.setObjectName("mplRiver")
        self.tabs.addTab(self.riverTab, "")
        self.fourierTab = QtWidgets.QWidget()
        self.fourierTab.setObjectName("fourierTab")
        self.mplRiver_2 = MplWidget(self.fourierTab)
        self.mplRiver_2.setGeometry(QtCore.QRect(0, 0, 761, 761))
        self.mplRiver_2.setMinimumSize(QtCore.QSize(500, 500))
        self.mplRiver_2.setAutoFillBackground(True)
        self.mplRiver_2.setObjectName("mplRiver_2")
        self.tabs.addTab(self.fourierTab, "")
        self.phaseTab = QtWidgets.QWidget()
        self.phaseTab.setObjectName("phaseTab")
        self.mplRiver_3 = MplWidget(self.phaseTab)
        self.mplRiver_3.setGeometry(QtCore.QRect(0, 0, 761, 761))
        self.mplRiver_3.setMinimumSize(QtCore.QSize(500, 500))
        self.mplRiver_3.setAutoFillBackground(True)
        self.mplRiver_3.setObjectName("mplRiver_3")
        self.tabs.addTab(self.phaseTab, "")
        self.pdTab = QtWidgets.QWidget()
        self.pdTab.setObjectName("pdTab")
        self.mplRiver_4 = MplWidget(self.pdTab)
        self.mplRiver_4.setGeometry(QtCore.QRect(0, 0, 761, 761))
        self.mplRiver_4.setMinimumSize(QtCore.QSize(500, 500))
        self.mplRiver_4.setAutoFillBackground(True)
        self.mplRiver_4.setObjectName("mplRiver_4")
        self.tabs.addTab(self.pdTab, "")
        self.steadyTab = QtWidgets.QWidget()
        self.steadyTab.setObjectName("steadyTab")
        self.mplRiver_5 = MplWidget(self.steadyTab)
        self.mplRiver_5.setGeometry(QtCore.QRect(0, 0, 761, 761))
        self.mplRiver_5.setMinimumSize(QtCore.QSize(500, 500))
        self.mplRiver_5.setAutoFillBackground(True)
        self.mplRiver_5.setObjectName("mplRiver_5")
        self.tabs.addTab(self.steadyTab, "")
        experimentWindow.setCentralWidget(self.centralWidge)
        self.menubar = QtWidgets.QMenuBar(experimentWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1229, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuUndo = QtWidgets.QMenu(self.menubar)
        self.menuUndo.setObjectName("menuUndo")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        experimentWindow.setMenuBar(self.menubar)
        self.actionSave = QtWidgets.QAction(experimentWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(experimentWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionUndo = QtWidgets.QAction(experimentWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(experimentWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionPreferences = QtWidgets.QAction(experimentWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionPreferences_2 = QtWidgets.QAction(experimentWindow)
        self.actionPreferences_2.setObjectName("actionPreferences_2")
        self.actionFullscreen = QtWidgets.QAction(experimentWindow)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionMinimize = QtWidgets.QAction(experimentWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuUndo.addAction(self.actionUndo)
        self.menuUndo.addAction(self.actionRedo)
        self.menuUndo.addSeparator()
        self.menuView.addAction(self.actionFullscreen)
        self.menuView.addAction(self.actionMinimize)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuUndo.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(experimentWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(experimentWindow)

    def retranslateUi(self, experimentWindow):
        _translate = QtCore.QCoreApplication.translate
        experimentWindow.setWindowTitle(_translate("experimentWindow", "MainWindow"))
        self.settingsFrame.setStatusTip(_translate("experimentWindow", "Experiment settings"))
        self.settingsFrame.setTitle(_translate("experimentWindow", "Experiment Settings:"))
        self.unameInput.setStatusTip(_translate("experimentWindow", "Input user name"))
        self.expNum.setStatusTip(_translate("experimentWindow", "Set experiment number"))
        self.expNum.setText(_translate("experimentWindow", "Experiment #:"))
        self.unameLabel.setText(_translate("experimentWindow", "User Name:"))
        self.label_13.setStatusTip(_translate("experimentWindow", "Experiment number"))
        self.label_13.setText(_translate("experimentWindow", "1"))
        self.defaultCheck.setStatusTip(_translate("experimentWindow", "Check for default options"))
        self.defaultCheck.setText(_translate("experimentWindow", "Check for default"))
        self.commFrame.setStatusTip(_translate("experimentWindow", "Communication Settings"))
        self.commFrame.setTitle(_translate("experimentWindow", "Communication Settings:"))
        self.teensyInput.setStatusTip(_translate("experimentWindow", "Input user name"))
        self.teensyInput.setPlaceholderText(_translate("experimentWindow", "4"))
        self.integration.setText(_translate("experimentWindow", "Integration Time:"))
        self.checkBox_2.setStatusTip(_translate("experimentWindow", "Check for default"))
        self.checkBox_2.setText(_translate("experimentWindow", "Check for default"))
        self.integrationInput.setStatusTip(_translate("experimentWindow", "Input user name"))
        self.integrationInput.setPlaceholderText(_translate("experimentWindow", "7"))
        self.teensyPort.setText(_translate("experimentWindow", "Teensy Port #:"))
        self.uploadFile.setStatusTip(_translate("experimentWindow", "Upload an excel file with experiment parameters"))
        self.uploadFile.setText(_translate("experimentWindow", "Upload Experiment File"))
        self.startButton.setStatusTip(_translate("experimentWindow", "Start running the experiment"))
        self.startButton.setText(_translate("experimentWindow", "Start Experiment"))
        self.saveBox.setTitle(_translate("experimentWindow", "Save CSV Files"))
        self.phaseCheck.setText(_translate("experimentWindow", "Phase"))
        self.fourierCheck.setText(_translate("experimentWindow", "Fourier"))
        self.pdCheck.setText(_translate("experimentWindow", "Phase Derivative"))
        self.riverCheck.setText(_translate("experimentWindow", "River Plot"))
        self.riverLoc.setText(_translate("experimentWindow", "PushButton"))
        self.fourierLoc.setText(_translate("experimentWindow", "PushButton"))
        self.phaseLoc.setText(_translate("experimentWindow", "PushButton"))
        self.pdLoc.setText(_translate("experimentWindow", "PushButton"))
        self.saveCheck.setText(_translate("experimentWindow", "Check for defaults"))
        self.plotFrame.setAccessibleName(_translate("experimentWindow", "Plot Frame"))
        self.plotFrame.setAccessibleDescription(_translate("experimentWindow", "Frame containing tabs for experiment plots"))
        self.tabs.setStatusTip(_translate("experimentWindow", "Plot tabs"))
        self.riverTab.setStatusTip(_translate("experimentWindow", "Plotting River Plot"))
        self.tabs.setTabText(self.tabs.indexOf(self.riverTab), _translate("experimentWindow", "River Plot"))
        self.fourierTab.setStatusTip(_translate("experimentWindow", "Plotting first frequency of fourier transfrom"))
        self.tabs.setTabText(self.tabs.indexOf(self.fourierTab), _translate("experimentWindow", "Fourier"))
        self.phaseTab.setStatusTip(_translate("experimentWindow", "Plotting phase of spectrum"))
        self.tabs.setTabText(self.tabs.indexOf(self.phaseTab), _translate("experimentWindow", "Phase"))
        self.pdTab.setStatusTip(_translate("experimentWindow", "Plotting phase derivative"))
        self.tabs.setTabText(self.tabs.indexOf(self.pdTab), _translate("experimentWindow", "Phase Derivative"))
        self.steadyTab.setStatusTip(_translate("experimentWindow", "Plotting steady state condition and peaks"))
        self.tabs.setTabText(self.tabs.indexOf(self.steadyTab), _translate("experimentWindow", "Steady State"))
        self.menuFile.setTitle(_translate("experimentWindow", "File"))
        self.menuUndo.setTitle(_translate("experimentWindow", "Edit"))
        self.menuView.setTitle(_translate("experimentWindow", "View"))
        self.actionSave.setText(_translate("experimentWindow", "Save"))
        self.actionExit.setText(_translate("experimentWindow", "Exit"))
        self.actionUndo.setText(_translate("experimentWindow", "Undo"))
        self.actionRedo.setText(_translate("experimentWindow", "Redo"))
        self.actionPreferences.setText(_translate("experimentWindow", "Preferences"))
        self.actionPreferences_2.setText(_translate("experimentWindow", "Preferences"))
        self.actionFullscreen.setText(_translate("experimentWindow", "Fullscreen"))
        self.actionMinimize.setText(_translate("experimentWindow", "Minimize"))
from mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    experimentWindow = QtWidgets.QMainWindow()
    ui = Ui_experimentWindow()
    ui.setupUi(experimentWindow)
    experimentWindow.show()
    sys.exit(app.exec_())
